services:
  automation-selenium-tests:
    image: pytest_selenium_runner
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/Automation_project/
    command: pytest -sv --alluredir=allure_results/ /Automation_project/tests
    environment:
      - IS_START_DOCKER=true
      - LOGIN=${LOGIN}
      - PASSWORD=${PASSWORD}

# Запуск тестов: docker-compose up (можно добавить ключ -d, значит в фоне)

# Формирование отчета: docker-compose run automation-selenium-tests /bin/bash -c "allure generate allure_results --clean -o allure_report"